#!/usr/bin/env python3
"""Diff harvested @model ids (registry/blocks.json) against the authoritative
model list (registry/reference-models.json) to report which blocks we have
captured an id for and which we still need. Writes docs/reference/data-coverage.md.

Matching (see docs/naming-and-registry.md):
  1. reference-models.json "name_overrides" wins — a curated crosswalk of
     {display name -> @model id, or null if we don't have it} for names the
     heuristic can't resolve (abbreviations like "Lo Res" vs id "LowRes", generic
     names like "Stereo", or ids that don't derive from the label). This is also
     where a reference name's real on-device display name is recorded when it
     differs (the 'display_name' / 'note' fields).
  2. Otherwise TOKEN-SUBSET: tokenize the display name and each id (splitting
     acronyms, camelCase, letter/digit boundaries, dropping stopwords). A model is
     captured if the name's token set is a subset of some id's tokens.
  3. GUARD: a name whose tokens are all "generic" (stereo, mono, delay, pan, ...)
     is not credited by the heuristic — it must be in name_overrides.

Usage:  python3 tools/coverage.py
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import podgo

STOP = {"and", "the", "with", "of", "a", "an", "w", "legacy"}
GENERIC = {"stereo", "mono", "delay", "reverb", "dist", "distortion", "amp",
           "cab", "comp", "mod", "ring", "pan", "vol", "eq"}


def tokens(s):
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", s)      # acronym: USDouble->US Double
    s = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", s)           # camelCase
    s = re.sub(r"(?<=[A-Za-z])(?=[0-9])", " ", s)        # letter->digit
    s = re.sub(r"(?<=[0-9])(?=[A-Za-z])", " ", s)        # digit->letter
    return {t for t in re.split(r"[^a-z0-9]+", s.lower()) if t and t not in STOP}


def main():
    blocks = json.load(open(os.path.join(podgo.REPO, "registry", "blocks.json")))
    ref = json.load(open(os.path.join(podgo.REPO, "registry", "reference-models.json")))
    harvested = list(blocks["models"])
    harvested_set = set(harvested)
    id_tokens = [(m, tokens(m)) for m in harvested]
    overrides = {k: v for k, v in ref.get("name_overrides", {}).items() if not k.startswith("_")}

    def match_id(name):
        """Return the @model id this reference name maps to, or None."""
        if name in overrides:
            mid = overrides[name].get("model_id")
            return mid if (mid and mid in harvested_set) else None
        nt = tokens(name)
        if not nt or nt <= GENERIC:
            return None
        for m, it in id_tokens:
            if nt <= it:
                return m
        return None

    lines = ["# Block Data Coverage & Gap Worklist", "",
             f"Authoritative list: POD Go firmware {ref['firmware']}. "
             "✅ = we have captured its internal `@model` id; ⬜ = still need a "
             "data-preset that uses this block.", "",
             "Generated by `tools/coverage.py` (token-subset matching + the "
             "`name_overrides` crosswalk in registry/reference-models.json).", ""]
    total_have = total_all = 0
    summary = []
    for cat, data in ref["categories"].items():
        names = data["models"]
        have = sum(match_id(n) is not None for n in names)
        total_have += have
        total_all += len(names)
        summary.append((cat, have, len(names)))
        lines.append(f"## {cat}  —  {have}/{len(names)} captured")
        if data.get("note"):
            lines.append(f"_{data['note']}_")
        lines.append("")
        for n in names:
            lines.append(f"- {'✅' if match_id(n) else '⬜'} {n}")
        lines.append("")

    # Name <-> id divergences, from name_overrides (where actual differs from label)
    div = []
    for name, info in overrides.items():
        mid, disp, note = info.get("model_id"), info.get("display_name"), info.get("note")
        if info.get("display_name"):
            div.append(f"- **{name}** — on-device display: **{disp}**"
                       + (f"; id `{mid}`" if mid else "") + (f" ({note})" if note else ""))
        elif mid and note:
            div.append(f"- **{name}** → `{mid}` — {note}")
    if div:
        lines.append("## Name ↔ internal-id divergences")
        lines.append("Reference labels whose actual @model id (or on-device display name) "
                     "differs from the label. Maintained in `registry/reference-models.json`.")
        lines.append("")
        lines.extend(sorted(div))
        lines.append("")

    lines.insert(4, "| Category | Captured | Total |\n| --- | ---: | ---: |\n" +
                 "\n".join(f"| {c} | {h} | {t} |" for c, h, t in summary) +
                 f"\n| **TOTAL** | **{total_have}** | **{total_all}** |\n")

    dest = os.path.join(podgo.REPO, "docs", "reference", "data-coverage.md")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "w").write("\n".join(lines) + "\n")
    print(f"Wrote {os.path.relpath(dest, podgo.REPO)}")
    print(f"\nCaptured {total_have}/{total_all} authoritative models; "
          f"{len(div)} name/id divergences tracked\n")
    for c, h, t in summary:
        gap = t - h
        print(f"  {c:14} {h:3}/{t:<3}" + (f"   need {gap}" if gap else "   complete"))


if __name__ == "__main__":
    main()
