"""gen_usb_id_map — regenerate registry/usb-id-map.json from POD Go Edit's PodGo.sym.

THE usb_id → @model mapping is derivable directly from the app, no captures needed:

    usb_id == the 0-based index of a model's symbolicID in Resources/PodGo.sym

POD Go Edit loads PodGo.sym (627 JSON entries, each {symbol, parameters}) into a
`HelixSymbolTable` via `HelixSymbolTable::initFromTableData`; the array position IS the id,
and `HelixSymbolTable::lookupModel(symbolicID)` returns it. Confirmed on hardware, firmware
v2.50: a blind predictive test set the amp to "US Double Nrm" (PodGo.sym[41]) and the wire
carried exactly `c2 19 29` (0x29 = 41); plus 21 retrospective capture pairs all match.
See docs/reference/usb-id-mapping.md.

This tool reads PodGo.sym, self-checks against the known hardware pairs (aborts if any
mismatch — a guard against a future PodGo.sym reordering), and writes registry/usb-id-map.json.
Needs POD Go Edit installed (or POD_GO_EDIT_RESOURCES set), like the other catalog tools.

Usage:  python3 tools/gen_usb_id_map.py            # rewrite registry/usb-id-map.json
        python3 tools/gen_usb_id_map.py --check    # verify only; do not write
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "registry", "usb-id-map.json")

# Hardware-derived anchors (symbolicID -> usb_id) the generated map MUST reproduce.
# Sources: the prior registry map (calibration captures) + this-session set-model captures,
# incl. the predictive test (41) and the two spelling/variant clarifications.
KNOWN = {
    "HD2_DelaySimpleDelayStereo": 84, "HD2_DistVerminDistMono": 98,
    "HD2_CompressorDeluxeCompMono": 99, "HD2_FilterMutantFilterStereo": 117,
    "HD2_VolPanVolStereo": 224, "HD2_TremoloTremoloStereo": 249,
    "HD2_AmpDelSol300": 289, "HD2_CompressorAutoSwellMono": 304,
    "HD2_EQ_STATIC_ParametricStereo": 472, "HD2_CabMicIr_2x15Brute": 552,
    "HD2_AmpLine6Litigator": 286, "HD2_DistScream808Mono": 93,
    "HD2_DistMinotaurMono": 92, "HD2_CabMicIr_4x12Greenback25": 551,
    "HD2_AmpUSDoubleNrm": 41,               # blind predictive on-device confirmation
    "HD2_LooperMono": 127, "HD2_LooperOneSwitchMono": 430,
}


def resources_dir():
    d = os.environ.get("POD_GO_EDIT_RESOURCES") or \
        "/Applications/Line6/POD Go Edit.app/Contents/Resources"
    if not os.path.isdir(d):
        sys.exit(f"POD Go Edit resources not found at {d!r}. Install POD Go Edit or set "
                 f"POD_GO_EDIT_RESOURCES to its Contents/Resources directory.")
    return d


def load_sym(res):
    sym = json.load(open(os.path.join(res, "PodGo.sym"), encoding="utf-8"))
    return [e["symbol"] for e in sym]                    # index -> symbolicID (== usb_id -> @model)


def catalog_symbolic_ids(res):
    """symbolicIDs that PodGoModelDefs.bin exposes as user-selectable models (for a coverage note)."""
    try:
        import msgpack
    except ImportError:
        return None
    raw = open(os.path.join(res, "PodGoModelDefs.bin"), "rb").read()
    defs = msgpack.unpackb(raw, raw=True, strict_map_key=False)   # .bin strings are NUL-terminated
    out = set()
    for m in defs:
        if isinstance(m, dict):
            for k, v in m.items():          # keys AND values are NUL-terminated
                if k.rstrip(b"\x00") == b"symbolicID" and v:
                    out.add(v.rstrip(b"\x00").decode("utf-8", "replace"))
    return out


def verify(symbols):
    bad = [(sid, want, symbols[want] if want < len(symbols) else "<oob>")
           for sid, want in KNOWN.items()
           if want >= len(symbols) or symbols[want] != sid]
    return bad


def main():
    res = resources_dir()
    symbols = load_sym(res)
    bad = verify(symbols)
    if bad:
        print("VERIFY FAILED — PodGo.sym index no longer matches known hardware pairs:")
        for sid, want, got in bad:
            print(f"  usb {want}: expected {sid}, PodGo.sym has {got}")
        sys.exit("Refusing to write a map that contradicts hardware. Investigate PodGo.sym order.")
    print(f"PodGo.sym: {len(symbols)} entries; verified {len(KNOWN)}/{len(KNOWN)} hardware pairs.")

    cat = catalog_symbolic_ids(res)
    in_catalog = sum(1 for s in symbols if cat and s in cat) if cat else None
    if in_catalog is not None:
        print(f"of these, {in_catalog} are in PodGoModelDefs.bin (user-selectable catalog).")

    if "--check" in sys.argv[1:]:
        print("--check: not writing.")
        return

    doc = {
        "_comment": "usb_id -> @model, COMPLETE. usb_id == the 0-based index of a model's "
                    "symbolicID in POD Go Edit's Resources/PodGo.sym (loaded into a "
                    "HelixSymbolTable; the array position IS the id). Generated by "
                    "tools/gen_usb_id_map.py. See docs/reference/usb-id-mapping.md.",
        "status": f"complete ({len(symbols)}/{len(symbols)}) — derived from PodGo.sym; "
                  "hardware-confirmed (predictive: US Double Nrm -> 41) + 21 retro capture pairs",
        "decode": "to read a usb_id off a USB capture: within an occupied slot section find "
                  "'c2 19', then read a msgpack uint (fixint <0x80, 0xcc=uint8, 0xcd=uint16 BE) "
                  "before the '1aff09' marker. The Looper uses '84 08 <uint> 09'. That value is "
                  "the usb_id; @model = PodGo.sym[usb_id].",
        "derivation": "The map is NOT in PodGoModelDefs.bin/PGModelCatalog (no id field) but IS "
                      "in PodGo.sym as the entry order. HelixSymbolTable::lookupModel(symbolicID) "
                      "returns the index; lookupModel(uint) is the reverse. usb_id is thus the "
                      "Helix/HX global model index (monotonic with PodGo.sym order, which is why "
                      "it is NOT the PodGoModelDefs.bin array index).",
        "source": f"PodGo.sym ({len(symbols)} entries), POD Go Edit 2.50",
        "catalog_selectable": in_catalog,
        "count": len(symbols),
        "map": {str(i): s for i, s in enumerate(symbols)},
    }
    json.dump(doc, open(OUT, "w", encoding="utf-8"), indent=2)
    open(OUT, "a").write("\n")
    print(f"wrote {OUT}  ({len(symbols)} pairs)")


if __name__ == "__main__":
    main()
